package io.vulpine.lib.json.schema.v4.lib;

public interface Keys {
  String
    $REF        = "$ref",
    $SCHEMA     = "$schema",
    ADDTL_ITEMS = "additionalItems",
    ADDTL_PROPS = "additionalProperties",
    ALL_OF      = "allOf",
    ANY_OF      = "anyOf",
    DEFAULT     = "default",
    DEFINITIONS = "definitions",
    DESC        = "description",
    ENUM        = "enum",
    EXCL_MAX    = "exclusiveMaximum",
    EXCL_MIN    = "exclusiveMinimum",
    FORMAT      = "format",
    ID          = "id",
    ITEMS       = "items",
    MAX_ITEMS   = "maxItems",
    MAX_LENGTH  = "maxLength",
    MAX_PROPS   = "maxProperties",
    MAXIMUM     = "maximum",
    MIN_ITEMS   = "minItems",
    MIN_LENGTH  = "minLength",
    MIN_PROPS   = "minProperties",
    MINIMUM     = "minimum",
    MULTIPLE    = "multipleOf",
    NOT         = "not",
    ONE_OF      = "oneOf",
    PATTERN     = "pattern",
    PATT_PROPS  = "patternProperties",
    PROPS       = "properties",
    REQ         = "required",
    TITLE       = "title",
    TYPE        = "type",
    UNIQUE      = "uniqueItems";
}
